### ISSUE TITLE
Bug: should import type of `InjectionKey`

### ISSUE THREAD

**Issue by devRickyyy** [casdoor/casdoor-vue-sdk#18]
### Description
the type `InjectionKey` from `vue3` is including with the wrong way.
### Screenshots
<a href="https://ibb.co/N934g5C"><img src="https://i.ibb.co/sKPBpnR/20221020-010043.png" alt="20221020-010043" border="0"></a>

**Comment by leo220yuyaodog** [comment]
Can you provider a release package for us to test? Now the sdk works well, after modifing, I can not confirm if it will work well.
