### ISSUE TITLE
Best practice

### ISSUE THREAD

**Issue by Kingside88** [casdoor/casdoor-vue-sdk#20]
I'm sorry for asking again but I'm just stuck.
With importing Casdoor I have these functions to use:
getSignupUrl(), getSigninUrl(), getUserProfileUrl(), getMyProfileUrl(), signin()

But how to check if the user is logged in? Or the user is not deleted in the mean time.
How to check if the current user is authorized to do something?
Can you please provide a real example? Maybe I can help you with that?
I could upload an easy nuxt 3 project connecting to my demo casdoor

**Comment by hsluoyz** [comment]
@Kingside88 it usually is done by the backend code. The backend gets access token by: https://casdoor.org/docs/how-to-connect/sdk#4-get-and-verify-access-token , the token is JWT, extract user info from the JWT and store it to your app's session (like via cookie). Call these APIs to get real-time user info: https://casdoor.org/docs/how-to-connect/sdk#5-optional-interact-with-the-user-table

**Comment by Kingside88** [comment]
I am not really familar with Go lang but as long as I understand:
In this file  https://github.com/casbin/casnode/blob/6d4c55f5c9a3c4bd8c85f2493abad3553b9c7ac0/controllers/account.go
 it uses the GetOAuthToken and ParseJwtToken functions from casdoor-sdk.
Which itself call the global api:
https://github.com/casdoor/casdoor-go-sdk/blob/master/casdoorsdk/token.go

The global api itself has unmanageable CORS restrictions. Whereas on applicationlevel you can provide access for single domains.

**Comment by hsluoyz** [comment]
> But how to check if the user is logged in?

The application itself maintains the logged in session. Casdoor is mainly an OAuth provider.

> How to check if the current user is authorized to do something?

See: https://casdoor.org/docs/permission/overview

> Can you please provide a real example?

We already provide a lot of examples for nearly each language, see "Example code" part at: https://casdoor.org/docs/how-to-connect/sdk

> I could upload an easy nuxt 3 project connecting to my demo casdoor

You can provide a link to your repo, we can work out a way to add 3rd-party examples to the docs site

**Comment by mr-m0nst3r** [comment]
I got the same problem.

I'm using fastapi.

There's a `get-account` endpoint in the backend, which is checking whether there's a session accordingly.
When the user just visited the website, I saw a cookie for localhost: `casdoor_session_id: 849561b2b7b07a6fd0e24cce6e0850b6`

so, the fastapi receives this cookie any no more other info, when the frontend app send `get-account` requests.

My question is, is there any way to verify whether the `casdoor_session_id` is valid or not, or to get the logon user? so I don't have to use Sessions in fastapi, and let casdoor manage Sessions for me.

Thanks in advance.

**Comment by hsluoyz** [comment]
@mr-m0nst3r hi, this is not the correct place. Plz create issue at: https://github.com/casdoor/casdoor-python-sdk/issues

**Comment by mr-m0nst3r** [comment]
@hsluoyz ah, sorry, I'll post to there.

**Comment by hsluoyz** [comment]
Posted here: https://github.com/casdoor/casdoor-python-sdk/issues/40
