### ISSUE TITLE
Could not resolve... error after update to latest release

### ISSUE THREAD

**Issue by stefanwuthrich** [casdoor/casdoor-vue-sdk#24]
I update to latest release from 3. March and get the error below. Same happens also happens with a fresh yarn install after deleting node_modules

`
✘ [ERROR] Could not resolve "/home/runner/work/casdoor-vue-sdk/casdoor-vue-sdk/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js"

    node_modules/casdoor-vue-sdk/src/CasdoorSDK.js:1:30:
      1 │ ...asyncToGenerator from "/home/runner/work/casdoor-vue-sdk/casdoor-vue-sdk/node_modules/@babel/runtime/helpers/esm/asyncT...
        ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "regenerator-runtime/runtime.js"

    node_modules/casdoor-vue-sdk/src/CasdoorSDK.js:2:7:
      2 │ import "regenerator-runtime/runtime.js";
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "regenerator-runtime/runtime.js" as external to exclude it from the bundle,
  which will remove this error.

`

**Comment by stefanwuthrich** [comment]
npm: 9.1.3
node: v16.16.0v
yarn: v1.22.19

**Comment by hsluoyz** [comment]
@stefanwuthrich hi, can you check starting from which release this issue happens? https://github.com/casdoor/casdoor-vue-sdk/releases

**Comment by stefanwuthrich** [comment]
@hsluoyz from 1.4.0

**Comment by hsluoyz** [comment]
@jakiuncle @imp2002

**Comment by stefanwuthrich** [comment]
Confirm its fixed. Thank you, guys
